### ISSUE TITLE
EW4 A white old door window size loading file

### ISSUE THREAD

**Issue by aktiengeier91** [GarlicBread42/GETS_AlpineAddon#1]
The loading file of the EW IV A white old coach has a different door window size. It‘s 2 voxels longer in height (also compared to the EW IV A green). I assume this is not intended.

![IMG_0752](https://github.com/GarlicBread42/GETS_AlpineAddon/assets/66421418/b85a416c-b3e8-4231-86b1-8074782af9e6)
![IMG_0750](https://github.com/GarlicBread42/GETS_AlpineAddon/assets/66421418/bd37c4f5-569f-4a04-bbe0-24cc3a9581a8)

fixing it myself for my AS model, please fix for the A and others (if applicable)

cheers

**Comment by GarlicBread42** [comment]
sprites corrected
